#Country.create(name: "India", population: 16.6)
#Country.create(name: "Mexico", population: 13)
#Country.create(name: "Russia", population: 10.6)
#Country.create(name: "China", population: 10)
#Country.create(name: "Bangladesh", population: 7.5)
#Country.create(name: "Syria", population: 6.9)
#Country.create(name: "Pakistan", population: 6)
#Country.create(name: "Ukraine", population: 5.9)
#Country.create(name: "Philippines", population: 5.7)
#Country.create(name: "UK", population: 4.9)

Country.create(name: "Syria", population: 6309000)
Country.create(name: "Afghanistan", population: 2624000)
Country.create(name: "South Sudan", population: 2440000)
Country.create(name: "Myanmar", population: 1157000)
Country.create(name: "Somalia", population: 986000)
Country.create(name: "Sudan", population: 694000)
Country.create(name: "Congo", population: 621000)
Country.create(name: "Central African Republic", population: 546000)
Country.create(name: "Eritrea", population: 486000)
Country.create(name: "Burundi", population: 439000)
